[2024-04-09 21:25:00,298] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T20:19:07.865580+00:00 [queued]>
[2024-04-09 21:25:00,311] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T20:19:07.865580+00:00 [queued]>
[2024-04-09 21:25:00,312] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:25:00,313] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2024-04-09 21:25:00,313] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:25:00,331] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Descargar_datos_crudos> on 2024-04-09 20:19:07.865580+00:00
[2024-04-09 21:25:00,337] {standard_task_runner.py:52} INFO - Started process 595 to run task
[2024-04-09 21:25:00,342] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'Descargar_datos_crudos', 'manual__2024-04-09T20:19:07.865580+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpev4dz7px', '--error-file', '/tmp/tmp3kw0n8ut']
[2024-04-09 21:25:00,345] {standard_task_runner.py:80} INFO - Job 98: Subtask Descargar_datos_crudos
[2024-04-09 21:25:00,422] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T20:19:07.865580+00:00 [running]> on host c346f321fefe
[2024-04-09 21:25:00,506] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=Descargar_datos_crudos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-09T20:19:07.865580+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-09T20:19:07.865580+00:00
[2024-04-09 21:25:00,507] {logging_mixin.py:115} INFO - Hola
[2024-04-09 21:25:01,677] {logging_mixin.py:115} INFO - <Response [200]>
[2024-04-09 21:25:01,681] {python.py:173} INFO - Done. Returned value was: <Response [200]>
[2024-04-09 21:25:01,691] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-04-09 21:25:01,692] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2024-04-09 21:25:01,703] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=NEO_coderhouse, task_id=Descargar_datos_crudos, execution_date=20240409T201907, start_date=20240409T212500, end_date=20240409T212501
[2024-04-09 21:25:01,718] {standard_task_runner.py:97} ERROR - Failed to execute job 98 for task Descargar_datos_crudos (Object of type Response is not JSON serializable; 595)
[2024-04-09 21:25:01,765] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-09 21:25:01,805] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
