[2024-04-09 21:12:16,322] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T20:19:07.865580+00:00 [queued]>
[2024-04-09 21:12:16,421] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T20:19:07.865580+00:00 [queued]>
[2024-04-09 21:12:16,424] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:12:16,425] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2024-04-09 21:12:16,425] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-04-09 21:12:16,474] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): Descargar_datos_crudos> on 2024-04-09 20:19:07.865580+00:00
[2024-04-09 21:12:16,495] {standard_task_runner.py:52} INFO - Started process 181 to run task
[2024-04-09 21:12:16,501] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'NEO_coderhouse', 'Descargar_datos_crudos', 'manual__2024-04-09T20:19:07.865580+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpm1up74s3', '--error-file', '/tmp/tmp5i7tfd45']
[2024-04-09 21:12:16,507] {standard_task_runner.py:80} INFO - Job 87: Subtask Descargar_datos_crudos
[2024-04-09 21:12:16,812] {task_command.py:371} INFO - Running <TaskInstance: NEO_coderhouse.Descargar_datos_crudos manual__2024-04-09T20:19:07.865580+00:00 [running]> on host c346f321fefe
[2024-04-09 21:12:17,077] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=LukeFo
AIRFLOW_CTX_DAG_ID=NEO_coderhouse
AIRFLOW_CTX_TASK_ID=Descargar_datos_crudos
AIRFLOW_CTX_EXECUTION_DATE=2024-04-09T20:19:07.865580+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-04-09T20:19:07.865580+00:00
[2024-04-09 21:12:17,080] {logging_mixin.py:115} INFO - Hola
[2024-04-09 21:12:17,892] {python.py:173} INFO - Done. Returned value was: <Response [200]>
[2024-04-09 21:12:17,904] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-04-09 21:12:17,905] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2024-04-09 21:12:17,925] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=NEO_coderhouse, task_id=Descargar_datos_crudos, execution_date=20240409T201907, start_date=20240409T211216, end_date=20240409T211217
[2024-04-09 21:12:17,959] {standard_task_runner.py:97} ERROR - Failed to execute job 87 for task Descargar_datos_crudos (Object of type Response is not JSON serializable; 181)
[2024-04-09 21:12:18,024] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-04-09 21:12:18,421] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
